# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ruby2cext}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Dominik Bathon, rogerdpack"]
  s.date = %q{2009-09-29}
  s.default_executable = %q{rb2cx}
  s.email = %q{dbatml@gmx.de}
  s.executables = ["rb2cx"]
  s.extra_rdoc_files = [
    "Changelog",
     "README"
  ]
  s.files = [
    "Changelog",
     "README",
     "bin/rb2cx",
     "doc/style.css",
     "lib/concretizer.rb",
     "lib/ruby2cext/c_function.rb",
     "lib/ruby2cext/common_node_comp.rb",
     "lib/ruby2cext/compiler.rb",
     "lib/ruby2cext/concretize.rb",
     "lib/ruby2cext/error.rb",
     "lib/ruby2cext/eval2c.rb",
     "lib/ruby2cext/parser.rb",
     "lib/ruby2cext/plugin.rb",
     "lib/ruby2cext/plugins/builtin_methods.rb",
     "lib/ruby2cext/plugins/cache_call.rb",
     "lib/ruby2cext/plugins/case_optimize.rb",
     "lib/ruby2cext/plugins/const_cache.rb",
     "lib/ruby2cext/plugins/direct_self_call.rb",
     "lib/ruby2cext/plugins/inline_builtin.rb",
     "lib/ruby2cext/plugins/inline_methods.rb",
     "lib/ruby2cext/plugins/ivar_cache.rb",
     "lib/ruby2cext/plugins/require_include.rb",
     "lib/ruby2cext/plugins/util.rb",
     "lib/ruby2cext/plugins/warnings.rb",
     "lib/ruby2cext/scopes.rb",
     "lib/ruby2cext/str_to_c_strlit.rb",
     "lib/ruby2cext/tools.rb",
     "lib/ruby2cext/version.rb",
     "testfiles/Makefile",
     "testfiles/causes_crash_all_opts.rb",
     "testfiles/eval2c/test_eval2c.rb",
     "testfiles/test_all.rb",
     "testfiles/test_bootstrap.rb",
     "testfiles/test_concretize.rb",
     "testfiles/test_files/test.rb",
     "testfiles/test_files/vmode_test.rb",
     "testfiles/test_files/warn_test.rb"
  ]
  s.homepage = %q{http://ruby2cext.rubyforge.org/}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Ruby2CExtension is a Ruby to C extension translator/compiler.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rubynode>, [">= 0.1.1"])
      s.add_runtime_dependency(%q<rogerdpack-sane>, [">= 0"])
    else
      s.add_dependency(%q<rubynode>, [">= 0.1.1"])
      s.add_dependency(%q<rogerdpack-sane>, [">= 0"])
    end
  else
    s.add_dependency(%q<rubynode>, [">= 0.1.1"])
    s.add_dependency(%q<rogerdpack-sane>, [">= 0"])
  end
end
